server:
  port: 8761

spring:
  application:
    name: Service-Registry

#eureka configurations
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false