server:
  port: 8084


spring:
  application:
    name: Api-Gateway
  cloud:
      gateway:
        routes:
          - id: USER-MICROSERVICE
            uri: lb://USER-MICROSERVICE
            predicates:
              - Path= /users/**
          - id: HOTEL-MICROSERVICE
            uri: lb://HOTEL-MICROSERVICE
            predicates:
              - Path= /hotels/**

          - id: RATINGS-MICROSERVICE
            uri: lb://RATINGS-MICROSERVICE
            predicates:
              - Path= /ratings/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka