server:
  port: 8083

spring:
  application:
    name: Ratings-Microservice
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: ratingsdb

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
